

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ecommerce-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    networks:
      - ecommerce-net

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - JWT_SECRET_KEY=Frqa5001
      - JWT_EXPIRES=5m
    depends_on:
      - mongo
    networks:
      - ecommerce-net

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-net

networks:
  ecommerce-net:

volumes:
  mongo-data:
